### ISSUE TITLE
 Project overview webview not loading

### ISSUE THREAD

**Issue by sanihaq** [rafalou38/twop#4] opened 2022-08-03 10:19 UTC
opening "Tracked projects  overview" tab taking a lot of time. It was working the first few time I was using it but stop using after some time. opened a lot of other projects since then. so that could be the reason.

**Comment by rafalou38** [comment] 2022-08-03 16:12
Can you share the content of the console ?
(Command: toggle développer tools/Ctrl+shift+i)
And paste it in a pastebin or gist.
I'll see if I can optimize it.

**Comment by sanihaq** [comment] 2022-08-03 18:08
`workbench.desktop.main.js:2115 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///c%3A/Users/Sani/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///c%3A/Users/Sani/.vscode/extensions/dart-code.dart-code-3.46.1/syntaxes/dart.json

DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/3b889b0…/core/vs/base/parts/sandbox/electron-browser/preload.js.map: Load canceled due to load timeout

DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/3b889b0…/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/3b889b0…/core/vs/base/worker/workerMain.js.map: Load canceled due to load timeout

workbench.desktop.main.js:86 [Extension Host] TWOP: global DB: c:\Users\Sani\AppData\Roaming\Code\User\globalStorage\rafaelmartinez.twop\twop.db

workbench.desktop.main.js:86 [Extension Host] TWOP: local DB: c:\Users\Sani\AppData\Roaming\Code\User\workspaceStorage\5ba327ad9c8892747673c52f00d0f26b\rafaelmartinez.twop\twop.db`

**Comment by rafalou38** [comment] 2022-08-03 19:22
can you send this file `c:\Users\Sani\AppData\Roaming\Code\User\globalStorage\rafaelmartinez.twop\twop.db` that contains the global database of the extension so that I can see if it contains an error or is corrupted?
also does it take a long time to load or just never loads ? 
Your logs are normal and don't show any error from the extension.

**Comment by sanihaq** [comment] 2022-08-03 19:43
It actually never loads

<details>
<summary>Here whats in the db file</summary>

{"name":"wildrydes-site","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\07b363734984abe28fa72b0daef311c8\\rafaelmartinez.twop\\twop.db","path":"o:\\wildrydes-site","timestamp":1658863738546,"_id":"303KiL9ztGe0MVaT"}
{"name":"unpub","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\fb900674e5fc0dd5ef00be47dc63cf27\\rafaelmartinez.twop\\twop.db","path":"o:\\unpub","timestamp":1659380344957,"_id":"5Xnoz0cElG1JaVWy"}
{"name":"serverless-example-typescript","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\f002f5d805caa700da2b7a1918a73013\\rafaelmartinez.twop\\twop.db","path":"o:\\serverless-example-typescript","timestamp":1659031547764,"_id":"7SkqhePvBA6zl6C6"}
{"name":"node-amazon-cognito-oauth","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\f2d4424463d55115bdc55b55348a19dc\\rafaelmartinez.twop\\twop.db","path":"o:\\node-amazon-cognito-oauth","timestamp":1659029867660,"_id":"8ON4O2rROaY83nIJ"}
{"name":"unpub_1","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\67e138cdaff74d321de1f8ccc65a3579\\rafaelmartinez.twop\\twop.db","path":"o:\\packages\\unpub_1","timestamp":1659437824466,"_id":"9RzvPLA0sTVrpM9c"}
{"name":"unpub","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\fb900674e5fc0dd5ef00be47dc63cf27\\rafaelmartinez.twop\\twop.db","path":"o:\\unpub","timestamp":1659380344938,"_id":"BTZ1qRA4mzamQqib"}
{"name":"node-amazon-cognito-oauth","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\f2d4424463d55115bdc55b55348a19dc\\rafaelmartinez.twop\\twop.db","path":"o:\\node-amazon-cognito-oauth","timestamp":1659029867653,"_id":"KBPI78PaerxHFCwp"}
{"name":"unpub","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\fb900674e5fc0dd5ef00be47dc63cf27\\rafaelmartinez.twop\\twop.db","path":"o:\\unpub","timestamp":1659380344946,"_id":"RYEZBTCMJNNugfYu"}
{"name":"my-deno-fresh-project","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\5ba327ad9c8892747673c52f00d0f26b\\rafaelmartinez.twop\\twop.db","path":"o:\\my-deno-fresh-project","timestamp":1659121986342,"_id":"T1hVFTX3437oNNLP"}
{"name":"master","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\9eaaa4fc1890876fe7a13bebe6ebb9ee\\rafaelmartinez.twop\\twop.db","path":"o:\\_work\\_worktree\\unpub_pubpro.worktrees\\master","timestamp":1659385979456,"_id":"cw00rNCYgVlheJ47"}
{"name":"unpub","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\fb900674e5fc0dd5ef00be47dc63cf27\\rafaelmartinez.twop\\twop.db","path":"o:\\unpub","timestamp":1659380344966,"_id":"fWoWzXJLnXen7gUs"}
{"name":"backup","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\db47160e2d790b0048733f5f45805836\\rafaelmartinez.twop\\twop.db","path":"o:\\_work\\_worktree\\unpub_pubpro.worktrees\\backup","timestamp":1659385580851,"_id":"h9rHly1Oc3k0491k"}
{"name":"node-amazon-cognito-oauth","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\f2d4424463d55115bdc55b55348a19dc\\rafaelmartinez.twop\\twop.db","path":"o:\\node-amazon-cognito-oauth","timestamp":1659029867646,"_id":"hHJKCCZf42Z0tGn1"}
{"name":"my-deno-fresh-project","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\5ba327ad9c8892747673c52f00d0f26b\\rafaelmartinez.twop\\twop.db","path":"o:\\my-deno-fresh-project","timestamp":1659121986334,"_id":"oT61DYX8Z1EFICjS"}
{"name":"unpub","db":"c:\\Users\\Sani\\AppData\\Roaming\\Code\\User\\workspaceStorage\\fb900674e5fc0dd5ef00be47dc63cf27\\rafaelmartinez.twop\\twop.db","path":"o:\\unpub","timestamp":1659380344926,"_id":"uUV1KRbDJWCdXvza"}


</details>

**Comment by rafalou38** [comment] 2022-08-03 20:51
I think the bug might come from a deleted project

you should be able to solve that issue by closing all your vscode instances and deleting the global db (the file I asked).
It won't reset the timers but you will need to  reopen your projects to make them appear in the projects overview

But that doesn't really solve the cause of the issue 🤔 I'll investigate further on my side.

Until then check if doing so fixes your issue, if it does, close this issue and reopen it if it happens again

**Comment by sanihaq** [comment] 2022-08-04 03:51
Deleting twop.db does solve the problem. But it's not really a fix, more like a hack. Please keep working on it. Thanks.

**Closed as completed** 2022-08-04 03:52 UTC

**Comment by rafalou38** [comment] 2022-08-05 16:43
It should be fixed now!
